// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASO9QO5Rln9-eg76ucpQfLGhn2lloLDqU',
    appId: '1:167902460569:web:94ad9210b09c38200b5608',
    messagingSenderId: '167902460569',
    projectId: 'spellbooktest',
    authDomain: 'spellbooktest.firebaseapp.com',
    storageBucket: 'spellbooktest.appspot.com',
    measurementId: 'G-S2HTWC7W1Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2B-wDZauKn8pZmc8R2N5nRjZuEDsVrvM',
    appId: '1:167902460569:android:04c097876a2594470b5608',
    messagingSenderId: '167902460569',
    projectId: 'spellbooktest',
    storageBucket: 'spellbooktest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdpo_BbaPh0TA4Xt70Win4_YJj7djT-y8',
    appId: '1:167902460569:ios:6a5433f97383e0df0b5608',
    messagingSenderId: '167902460569',
    projectId: 'spellbooktest',
    storageBucket: 'spellbooktest.appspot.com',
    iosClientId: '167902460569-gq6ovcb3c2cdnecl55ic2k13d9k4kf04.apps.googleusercontent.com',
    iosBundleId: 'com.example.spellbook',
  );
}
